### ISSUE TITLE
[BUG] module "folder" not idempotent when setting attributes

### ISSUE THREAD

**Issue by joernclausen** [Checkmk/ansible-collection-tribe29.checkmk#289]
I'd like to create a folder with some attributes set:
```
    - name: create single folder
      folder:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        path: /compute/testme
        name: testme
        attributes:
          contactgroups:
            groups:
              - "testme-admin"
            recurse_perms: true
        state: present
      delegate_to: localhost
```
On first use, this task succeeds and does exactly what I want. Repeating this task leads to an error
```
fatal: [testps -> localhost]: FAILED! => {"changed": false, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: name\", \"fields\": {\"name\": [\"Unknown field.\"]}}', "}
```
Without the "attributes" part, the task is idempotent and works as expected.

**Comment by joernclausen** [comment]
Thanks for the information. I'll give it a try when the PR is merged.

**Comment by robin-tribe29** [comment]
@joernclausen `0.20.0` was just released. Happy testing. :)

**Comment by joernclausen** [comment]
Unfortunately, this did not fix the problem. Creating a new folder with the desired permissions still works, but the operation is still not idempotent.

**Comment by lgetwan** [comment]
I will check that, but I need some time.

**Comment by msekania** [comment]
@lgetwan @robin-checkmk 

One can "generalize" current `module:folder` similar to `module:host`. These might also solve the mentioned bug.
I can prepare pull request if no one is working currently on this issue.

**Comment by robin-checkmk** [comment]
@msekania that would be lovely, we are still swamped. Thank you!

**Comment by msekania** [comment]
@robin-checkmk 
There is a following problem:

input
```json
'contactgroups': {'groups': ['test_contact_group'], 'recurse_perms': True}
```

return value
```json
'contactgroups': {'groups': ['test_contact_group'], 'use': False, 'use_for_services': False, 'recurse_use': False, 'recurse_perms': True}
```

do not match although they mean the same!
Issues with returned default values.

module:host might be also affected

**Comment by msekania** [comment]
@robin-checkmk 

Yes, module:host has the same issue!

```yaml
    - name: create single folder
      folder:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "testhost"
        attributes:
          contactgroups:
            groups:
              - "testme-admin"
            recurse_perms: true
        state: present
      delegate_to: localhost
```
